#cloud-config

users:
  - name: ${username}
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}

packages:
  - fail2ban
  - ufw
package_update: true
package_upgrade: true

write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      Port ${ssh_port}
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      MaxAuthTries 2
      AllowTcpForwarding no
      X11Forwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys
      AllowUsers daniel

runcmd:
  # fail2ban prevent login for 10 mins
  - printf "[sshd]\nenabled = true\nport = ssh, 2222\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban

  # ufw allow ssh and tailscale connections
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ${ssh_port}
  - ufw allow 41641
  - ufw enable

  # tailscale
  # One-command install, from https://tailscale.com/download/
  - curl -fsSL https://tailscale.com/install.sh | sh
  # Set sysctl settings for IP forwarding (useful when configuring an exit node)
  - echo 'net.ipv4.ip_forward = 1' | tee -a /etc/sysctl.d/99-tailscale.conf
  - echo 'net.ipv6.conf.all.forwarding = 1' | tee -a /etc/sysctl.d/99-tailscale.conf
  - sysctl -p /etc/sysctl.d/99-tailscale.conf
  # Generate an auth key from your Admin console
  # https://login.tailscale.com/admin/settings/keys
  - tailscale up --auth-key=${tailscale_hetzner_api_key}
  - tailscale set --advertise-exit-node
  - tailscale set --operator=${username}

  - reboot
